apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ms-aumento-voto
spec:
  replicas: 3
  selector:
    matchLabels:
        app: ms-aumento-voto
    template:
      metadata:
        labels:
          app: ms-aumento-voto
      spec:
        containers:
        - name: ms-aumento-voto
          image: cristianaliaga/repo-image:latest
          ports:
          - containerPort: 8080
        