name: CI
on: 
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clonacion de Codigo
              uses: actions/checkout@v4

            - name: Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Compilacion
              run: |
                    #mvn package
                    echo 'package'

            - name: Analisis SonarCloud
              run: |
                mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
                -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=cristian-aliaga \
                -Dsonar.projectKey=cristian-aliaga_ms-aumento-voto
            
            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}