name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clonacion de Codigo
              uses: actions/checkout@v3

            - name: Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Compilacion
              run: |
                    #mvn package
                    echo 'package'
                    
            - name: Test Unitarios
              run: |
                mvn package test
            
            - name: Analisis SonarCloud
              run: |
                mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
                -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=cristian-aliaga \
                -Dsonar.projectKey=ms-aumento-voto
            
            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker Build
              run: |
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/repo-image:latest .

            - name: Docker Push
              run: |
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/repo-image:latest
    
    deploy:
            needs: build
            runs-on: self-hosted
                
            steps:
                - name: Clonacion de Codigo
                  uses: actions/checkout@v3
                - name: Despliegue Test Runner Kubernetes
                  run: |
                    kubectl apply -f deploy.yaml --validate=false --insecure-skip-tls-verify=true